# Generated by Django 4.2.20 on 2026-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0009_usersessionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
