# Generated by Django 4.2.20 on 2026-07-20 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0010_activeoperation_planned_finish_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "Completed"),
                            ("removed", "Removed"),
                            ("reassigned", "Reassigned"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("working", "Working"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments_created",
                        to="Backend.useraccount",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_assignments",
                        to="Backend.activeoperation",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_assignments",
                        to="Backend.useraccount",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="operatorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("operator",),
                name="unique_active_assignment_per_operator",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("operation",),
                name="unique_active_assignment_per_operation",
            ),
        ),
    ]
