# Generated by Django 4.2.20 on 2026-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Backend", "0012_pendinguserverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchSynchronization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="dispatch", max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("never", "Never synchronized"),
                            ("running", "Synchronization running"),
                            ("success", "Synchronization successful"),
                            ("error", "Synchronization failed"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("records_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DispatchOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.CharField(db_index=True, max_length=100)),
                ("order", models.CharField(db_index=True, max_length=100)),
                ("operation", models.CharField(db_index=True, max_length=100)),
                (
                    "operated_item",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reference_operation_machine_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("routing_quantity", models.FloatField(default=0)),
                (
                    "planned_start_date",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reference_operation_work_center",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "operation_status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("synchronized_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "operation"],
                "indexes": [
                    models.Index(
                        fields=["company_id", "order", "operation"],
                        name="dispatch_company_order_idx",
                    ),
                    models.Index(
                        fields=["company_id", "operation_status"],
                        name="dispatch_company_status_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dispatchoperation",
            constraint=models.UniqueConstraint(
                fields=("company_id", "order", "operation"),
                name="unique_dispatch_operation",
            ),
        ),
    ]
