# Generated by Django 4.2.20 on 2026-07-20 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_pendingpasswordchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('company_id', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.CharField(db_index=True, max_length=100)),
                ('operation', models.CharField(db_index=True, max_length=100)),
                ('qty_deliver', models.FloatField(default=0)),
                ('qty_reject', models.FloatField(default=0)),
                ('quality_score', models.FloatField(default=100)),
                ('points', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['username', 'completed_at'], name='operator_perf_user_date')],
            },
        ),
    ]
