# Generated by Django 4.2.20 on 2026-07-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_repair_activeoperation_columns'),
        ('Backend', '0016_useraccount_personal_settings'),
    ]

    operations = [
    ]
