# Generated by Django 4.2.20 on 2026-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_merge_20260722_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100, unique=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_type_value', models.CharField(max_length=100)),
                ('accounting_entity', models.CharField(max_length=100)),
                ('accounting_entity_value', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('location_value', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=100)),
                ('financial_company', models.CharField(max_length=100)),
                ('created_by', models.CharField(blank=True, default='', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=50)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'IDM_CONFIGURATION',
            },
        ),
    ]
